// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// rcpparma_hello_world
arma::mat rcpparma_hello_world();
RcppExport SEXP _cubeStats_rcpparma_hello_world() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpparma_hello_world());
    return rcpp_result_gen;
END_RCPP
}
// cubemean
arma::vec cubemean(const arma::Cube<double>& x);
RcppExport SEXP _cubeStats_cubemean(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::Cube<double>& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cubemean(x));
    return rcpp_result_gen;
END_RCPP
}
// intna
arma::Cube<int> intna(const arma::Cube<int>& x);
RcppExport SEXP _cubeStats_intna(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::Cube<int>& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(intna(x));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_cubeStats_rcpparma_hello_world", (DL_FUNC) &_cubeStats_rcpparma_hello_world, 0},
    {"_cubeStats_cubemean", (DL_FUNC) &_cubeStats_cubemean, 1},
    {"_cubeStats_intna", (DL_FUNC) &_cubeStats_intna, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_cubeStats(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
