# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_slicemean_int <- function(x, mis_val) {
    .Call(`_cubeStats_cpp_slicemean_int`, x, mis_val)
}

cpp_slicemean_num <- function(x, na_rm) {
    .Call(`_cubeStats_cpp_slicemean_num`, x, na_rm)
}

cpp_slicemax_int <- function(x, mis_val) {
    .Call(`_cubeStats_cpp_slicemax_int`, x, mis_val)
}

cpp_slicemax_num <- function(x, na_rm) {
    .Call(`_cubeStats_cpp_slicemax_num`, x, na_rm)
}

cpp_slicemin_int <- function(x, mis_val) {
    .Call(`_cubeStats_cpp_slicemin_int`, x, mis_val)
}

cpp_slicemin_num <- function(x, na_rm) {
    .Call(`_cubeStats_cpp_slicemin_num`, x, na_rm)
}

