# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpparma_hello_world <- function() {
    .Call(`_cubeStats_rcpparma_hello_world`)
}

#' Check function.
#'
#' @param x cube this is a test
#' @return  new vector
#' @export
cubemean <- function(x) {
    .Call(`_cubeStats_cubemean`, x)
}

intna <- function(x) {
    .Call(`_cubeStats_intna`, x)
}

