# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_slicemean_int <- function(x, na_rm, mis_val) {
    .Call(`_cubeStats_cpp_slicemean_int`, x, na_rm, mis_val)
}

cpp_slicemean_num <- function(x, na_rm) {
    .Call(`_cubeStats_cpp_slicemean_num`, x, na_rm)
}

cpp_slicemax_int <- function(x, na_rm, mis_val) {
    .Call(`_cubeStats_cpp_slicemax_int`, x, na_rm, mis_val)
}

cpp_slicemax_num <- function(x, na_rm) {
    .Call(`_cubeStats_cpp_slicemax_num`, x, na_rm)
}

cpp_slicemin_int <- function(x, na_rm, mis_val) {
    .Call(`_cubeStats_cpp_slicemin_int`, x, na_rm, mis_val)
}

cpp_slicemin_num <- function(x, na_rm) {
    .Call(`_cubeStats_cpp_slicemin_num`, x, na_rm)
}

cpp_slicemin_int2 <- function(x, mis_val) {
    .Call(`_cubeStats_cpp_slicemin_int2`, x, mis_val)
}

cpp_slicemin_num2 <- function(x, na_rm) {
    .Call(`_cubeStats_cpp_slicemin_num2`, x, na_rm)
}

cpp_slicemedian_int <- function(x, mis_val) {
    .Call(`_cubeStats_cpp_slicemedian_int`, x, mis_val)
}

cpp_slicemedian_num <- function(x, na_rm) {
    .Call(`_cubeStats_cpp_slicemedian_num`, x, na_rm)
}

cpp_slicesum_int <- function(x, na_rm, mis_val) {
    .Call(`_cubeStats_cpp_slicesum_int`, x, na_rm, mis_val)
}

cpp_slicesum_num <- function(x, na_rm) {
    .Call(`_cubeStats_cpp_slicesum_num`, x, na_rm)
}

cpp_slicegreater_int <- function(x, na_rm, value, mis_val) {
    .Call(`_cubeStats_cpp_slicegreater_int`, x, na_rm, value, mis_val)
}

cpp_slicegreater_num <- function(x, na_rm, value) {
    .Call(`_cubeStats_cpp_slicegreater_num`, x, na_rm, value)
}

cpp_sliceless_int <- function(x, na_rm, value, mis_val) {
    .Call(`_cubeStats_cpp_sliceless_int`, x, na_rm, value, mis_val)
}

cpp_sliceless_num <- function(x, na_rm, value) {
    .Call(`_cubeStats_cpp_sliceless_num`, x, na_rm, value)
}

cpp_slicerange_int <- function(x, na_rm, value1, value2, mis_val) {
    .Call(`_cubeStats_cpp_slicerange_int`, x, na_rm, value1, value2, mis_val)
}

cpp_slicerange_num <- function(x, na_rm, value1, value2) {
    .Call(`_cubeStats_cpp_slicerange_num`, x, na_rm, value1, value2)
}

cpp_sliceequal_int <- function(x, na_rm, value, mis_val) {
    .Call(`_cubeStats_cpp_sliceequal_int`, x, na_rm, value, mis_val)
}

cpp_sliceequal_num <- function(x, na_rm, value) {
    .Call(`_cubeStats_cpp_sliceequal_num`, x, na_rm, value)
}

cpp_tubemean_int <- function(x, mis_val) {
    .Call(`_cubeStats_cpp_tubemean_int`, x, mis_val)
}

cpp_tubemean_num <- function(x, na_rm) {
    .Call(`_cubeStats_cpp_tubemean_num`, x, na_rm)
}

